"""Regenerate narration.txt from scene.py so the two can never drift.

The code is the source of truth: Gaokao22Scene.verify_budget asserts that the
pause sequence each section actually emits equals its SCENE_BUDGET entry, and
SCENE_BUDGET is derived from the BEATS transcript. This script reads that same
transcript and writes narration.txt in the exact order the renderer will use,
with running timecodes so a voice actor can read straight down the page.

    python build_narration.py

Run it after changing any transcript line, adding a section, or editing a beat
duration. The output is stable, so it is safe to commit. CI regenerates it and
fails if the committed copy differs.
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import scene as production  # noqa: E402

OUTPUT = pathlib.Path("narration.txt")

HEADER = """THE 2008 JIANGXI GAOKAO PROBLEM -- NARRATION SCRIPT
===================================================

Generated by build_narration.py from scene.py. Do not hand-edit: the timecodes
below come from the live BEATS table, so recorded audio lines up with the render
automatically.

f(x,a) = 1/sqrt(1+x) + 1/sqrt(1+a) + sqrt(ax/(ax+8)),  x,a > 0
Prove 1 < f(x,a) < 2.

Sections : {sections}
Narration: {clock} ({total:.1f}s) of held narration, before animation time
Companion: scene_no_vo.py renders the same transcript as on-screen captions
"""


def clock(seconds: float) -> str:
    whole = int(round(seconds))
    return f"{whole // 60:d}:{whole % 60:02d}"


def build() -> str:
    body = [
        HEADER.format(
            sections=production.SECTION_COUNT,
            clock=clock(production.TOTAL_NARRATION),
            total=production.TOTAL_NARRATION,
        )
    ]
    at = 0.0
    for name in sorted(production.NARRATION, key=lambda s: int(s[1:])):
        beats = production.NARRATION[name]
        held = sum(d for _, _, d in beats)
        body.append(f"-- {name} " + "-" * max(0, 66 - len(name)))
        for _, text, dur in beats:
            body.append(f"  [{clock(at)} -> {clock(at + dur)}]  {text}")
            at += dur
        body.append(f"  (section narration {clock(held)}, running total {clock(at)})")
        body.append("")
    body.append("=" * 50)
    body.append(f"END - {clock(at)} of narration, {production.SECTION_COUNT} sections")
    return "\n".join(body) + "\n"


def main() -> int:
    OUTPUT.write_text(build(), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT}  ({production.TOTAL_NARRATION:.1f}s, "
          f"{sum(len(v) for v in production.NARRATION.values())} lines, "
          f"{production.SECTION_COUNT} sections)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
