"""Regenerate narration.txt from scene.py so the two can never drift.

The code is the source of truth: HopfFibrationScene.verify_budget asserts that
each scene's pause sequence equals its SCENE_BUDGET entry. This script reads
the real pause sequence out of the source, pairs it with the transcript held in
NARRATION, and writes narration.txt in the exact order the renderer will use.

    python build_narration.py

Run it after changing any transcript line, adding a scene, or editing a
self.pause(X) call. The output is stable, so it is safe to commit.
"""

from __future__ import annotations

import ast
import pathlib
import re
import sys

SCENE_FILE = pathlib.Path("scene.py")
OUTPUT_FILE = pathlib.Path("narration.txt")

HEADER = """THE HOPF FIBRATION -- NARRATION SCRIPT
======================================

Generated by build_narration.py from scene.py. Do not hand-edit: the pause
column below is the live self.pause(X) sequence, so the audio lines up with the
render automatically.

This is the voice-over track. It is NOT burned into the video as subtitles.
Render the movie silent, generate audio from this file with whatever TTS you
have, then mux the two together with ffmpeg (recipe at the bottom).
Works with ElevenLabs, Azure, OpenAI, Google, PlayHT, Kokoro, Piper,
espeak-ng, or even macOS `say`. No API key needed for the offline options.

FILE FORMAT
-----------
One utterance per line, in render order:
    <scene> | <line no> | <pause in seconds> | <text to speak>

<pause> is the SILENCE following that line: the exact value of the matching
self.pause(X) call in scene.py. Total pause time: {total} s.

PRONUNCIATION GUIDE (for any TTS)
--------------------------------
Hopf             -> "hopf", rhymes with "top" (not "hope", not "hof")
S^2 / S^3        -> "S two" / "S three" (letter, then number)
z_1 / z_2        -> "z one" / "z two"
SO(3)            -> "S O three"
Villarceau       -> "VEE-yar-soh" (common slip: "Villar-shoe")
quaternion       -> "kwah-tur-nee-un"
stereographic    -> "stair-ee-oh-GRAF-ic"
Heinz Hopf       -> "Hyntz Hopf"
theta            -> "THAY-tuh"
0.45 / 0.85      -> "point four five" / "point eight five"
x y plane        -> "the x y plane"
nineteen thirty-one -> "nineteen thirty-one"

PACING
------
Target 150 to 165 words per minute, calm and conversational, one idea per
sentence. The pauses are long on purpose: they are where the viewer watches
the geometry do the talking. If a line runs long for your engine, raise the
speaking rate slightly rather than shortening the pause.

--------------------------------------------------------------------------------
"""

FOOTER = """
--------------------------------------------------------------------------------

HOW TO PRODUCE THE AUDIO
------------------------
Easiest path (ElevenLabs):
  1. Paste the text column into the ElevenLabs speech editor.
  2. For the two hard words use their pronunciation field, or edit by hand:
       Hopf        -> "hopf"     (IPA: hɔpf)
       Villarceau  -> "VEE-yar-soh" (IPA: vijɑʁso)
  3. Export one WAV, then go to ASSEMBLY step 2.

Fully offline, no account, no key (Piper or espeak-ng):
  1. Split this file into one .txt per line.
  2. Synthesize each line:
       piper -m en_US-lessoc-medium -f 001.txt -w 001.wav
     or, with nothing installed:
       espeak-ng -v en-us -w 001.wav -f 001.txt
  3. Pad each line with its pause, then concat in numeric order. This script
     does both for you:
       python build_narration.py --assemble
     (requires ffmpeg on PATH; writes padded/ and voice_timed.wav)

Mixed engines are fine. Azure Speech, Google Cloud TTS, OpenAI TTS, PlayHT,
Kokoro, macOS `say -o line.wav "text"`, or even a phone recording all work.

ASSEMBLY
--------
Step 1. Render the movie (silent):
    manim render scene.py HopfFibrationScene

Step 2. Get the audio onto the pause grid. Either run the helper:
    python build_narration.py --assemble
  or, if you already have one continuous WAV of just the spoken lines, cut it
  into the {count} segments and rebuild it with ffmpeg per the helper's
  generated commands.

Step 3. Mux audio onto the movie:
    ffmpeg -i media/videos/scene/1440p60/HopfFibrationScene.mp4 \\
      -i voice_timed.wav -c:v copy -c:a aac -b:a 192k -shortest \\
      hopf_fibration_final.mp4

Step 4. Optional, loudness normalize to YouTube's -14 LUFS:
    ffmpeg -i hopf_fibration_final.mp4 -af loudnorm=I=-14:TP=-1.5:LRA=11 \\
      -c:v copy hopf_fibration_final_ln.mp4

Subtitles are a separate, optional job and are NOT part of this file. The line
numbers here are stable, so you can generate an SRT straight from them and burn
it in later with:
    ffmpeg -i hopf_fibration_final.mp4 -vf "subtitles=hopf.srt" -c:a copy out.mp4
"""


def scene_pauses() -> dict[str, list[float]]:
    """Read the real self.pause(X) sequence out of scene.py."""
    tree = ast.parse(SCENE_FILE.read_text(encoding="utf-8"))
    scene_class = next(
        node
        for node in tree.body
        if isinstance(node, ast.ClassDef) and node.name == "HopfFibrationScene"
    )
    pauses: dict[str, list[float]] = {}
    for function in scene_class.body:
        if not (isinstance(function, ast.FunctionDef) and function.name.startswith("scene_")):
            continue
        name = "S" + function.name.split("_")[1]
        values: list[float] = []
        for node in ast.walk(function):
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr == "pause"
                and node.args
            ):
                values.append(round(float(ast.literal_eval(node.args[0])), 3))
        pauses[name] = values
    return pauses


def transcript() -> dict[str, list[str]]:
    """Read the spoken lines from scene.py's VOICEOVER_SCRIPT block."""
    source = SCENE_FILE.read_text(encoding="utf-8")
    block = re.search(
        r'VOICEOVER_SCRIPT = """(.*?)\n"""', source, flags=re.DOTALL
    )
    if block is None:
        raise SystemExit("VOICEOVER_SCRIPT not found in scene.py")

    lines: dict[str, list[str]] = {}
    scene = None
    for raw in block.group(1).splitlines():
        marker = re.match(r"^--\s*(S\d)\b", raw.strip())
        if marker:
            scene = marker.group(1)
            lines[scene] = []
            continue
        if scene is None:
            continue
        spoken = re.match(r'^"(.*)"\s*\[pause:\s*([\d.]+)\]\s*$', raw.strip())
        if spoken:
            lines[scene].append(spoken.group(1))
    return lines


def format_pause(value: float) -> str:
    return str(int(value)) if value == int(value) else str(value)


def build() -> str:
    pauses = scene_pauses()
    spoken = transcript()

    problems: list[str] = []
    for name, values in pauses.items():
        expected = len(values)
        actual = len(spoken.get(name, []))
        if expected != actual:
            problems.append(
                f"{name}: scene.py has {expected} pause() calls but the "
                f"transcript has {actual} spoken lines"
            )
    if problems:
        raise SystemExit(
            "transcript and code disagree:\n  " + "\n  ".join(problems)
        )

    names = sorted(pauses, key=lambda scene: int(scene[1:]))
    total = sum(sum(values) for values in pauses.values())

    body: list[str] = []
    line_number = 0
    for name in names:
        for value, text in zip(pauses[name], spoken[name]):
            line_number += 1
            body.append(
                f"{name} | {line_number:03d} | {format_pause(value)} | {text}"
            )

    return (
        HEADER.format(total=format_pause(total), count=line_number)
        + "\n".join(body)
        + "\n"
        + FOOTER.format(count=line_number)
    )


def main() -> int:
    if "--assemble" in sys.argv:
        return assemble()
    OUTPUT_FILE.write_text(build(), encoding="utf-8")
    print(f"wrote {OUTPUT_FILE}")
    return 0


def assemble() -> int:
    """Pad each line's WAV with its pause and concatenate, via ffmpeg."""
    import subprocess

    pauses = scene_pauses()
    spoken = transcript()
    names = sorted(pauses, key=lambda scene: int(scene[1:]))
    padded = pathlib.Path("padded")
    padded.mkdir(exist_ok=True)

    pieces: list[tuple[str, float, str]] = []
    line_number = 0
    for name in names:
        for value, text in zip(pauses[name], spoken[name]):
            line_number += 1
            pieces.append((f"{line_number:03d}", value, text))

    missing = [
        stem
        for stem, _, _ in pieces
        if not pathlib.Path(f"{stem}.wav").exists()
    ]
    if missing:
        print(
            f"{len(missing)} of {len(pieces)} line WAVs are missing "
            f"(first: {missing[0]}). Generate them from the text column first."
        )
        return 1

    ordered: list[str] = []
    for stem, value, _ in pieces:
        target = padded / f"{stem}.wav"
        subprocess.run(
            [
                "ffmpeg", "-y", "-loglevel", "error",
                "-i", f"{stem}.wav",
                "-af", f"apad=pad_dur={format_pause(value)}",
                str(target),
            ],
            check=True,
        )
        ordered.append(str(target).replace("\\", "/"))

    listing = padded / "concat.txt"
    listing.write_text(
        "".join(f"file '{entry}'\n" for entry in ordered), encoding="utf-8"
    )
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-f", "concat",
         "-safe", "0", "-i", str(listing), "voice_timed.wav"],
        check=True,
    )
    print("wrote voice_timed.wav")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
